trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  inputs:
    filePath: 'etc/k8s/scripts/build-images.ps1'
    arguments: '-version $(Build.BuildId)'

- task: Docker@2
  inputs:
    containerRegistry: 'volocr'
    command: 'login'

- task: PowerShell@2
  inputs:
    filePath: 'etc/azure/scripts/push-images.ps1'
    arguments: '-version $(Build.BuildId)'

- task: HelmDeploy@0
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'volosoft(fe02ef9f-9e1c-4e40-b924-505981688dd8)'
    azureResourceGroup: 'volo'
    kubernetesCluster: 'volo'
    useClusterAdmin: true
    namespace: 'eventhub'
    command: 'upgrade'
    chartType: 'Name'
    chartName: 'etc/k8s/helm-chart/eventhub'
    releaseName: 'eh-az'
    valueFile: 'etc/k8s/helm-chart/eventhub/values.azure.yaml'
    arguments: '--namespace eventhub --create-namespace --set global.eventHubImageVersion=$(Build.BuildId)'