apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: account-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: "account.openeventhub.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: account
            port:
              number: 443