trigger:
- test

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '60b77638-6f87-431e-bf44-619404bd3935'
  imageRepository: 'voloeventhubidentityserver'
  containerRegistry: 'voloeventhubidentityserver.azurecr.io'
  dockerfilePath: '**/Dockerfile.EventHub.IdentityServer'
  tag: '$(Build.BuildNumber)'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - upload: manifests
      artifact: manifests

- stage: Deploy
  displayName: Deploy-Identity-Server
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'volosofteventhub-1068.default'
    strategy:
      runOnce:
        deploy:
          steps:
      

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.eventhub.identityserver.yml
                $(Pipeline.Workspace)/manifests/service.eventhub.identityserver.yml
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)

