trigger:
- test


variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '855289e7-1034-4e42-90b4-38c072ecefcb'
  imageRepository: 'voloeventhub'
  containerRegistry: 'voloeventhub.azurecr.io'
  dockerfilePath: '**/Dockerfile.EventHub.Web'
  tag: '$(Build.BuildNumber)'


  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - upload: manifests
      artifact: manifests

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy-EventHub-Web
    pool:
      vmImage: $(vmImageName)
    environment: 'volosofteventhub-3839.default'
    strategy:
      runOnce:
        deploy:
          steps:
       

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.eventhub.web.yml
                $(Pipeline.Workspace)/manifests/service.eventhub.web.yml
            
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)

