version: '3.7'

services:
  redis:
    image: redis:6.0.10-alpine
    networks:
      - eventhub-network      
  postgresql:
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    networks: 
      - eventhub-network

networks:
  eventhub-network:
    external: true