apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  activeDeadlineSeconds: 100
  template:
    spec:
      containers:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}
        image: eventhubmigrator
        imagePullPolicy: Never
      restartPolicy: Never
  backoffLimit: 4