global:
  accountDomain: eh-st-account
  accountUrl: https://eh-st-account
  apiDomain: eh-st-api
  apiUrl: https://eh-st-api
  wwwDomain: eh-st-www
  wwwUrl: "https://eh-st-www"
  adminDomain: eh-st-admin
  adminUrl: https://eh-st-admin
  adminApiDomain: eh-st-admin-api
  adminApiUrl: https://eh-st-admin-api
  nginxProxyBufferSize: "32k"
  nginxProxyBuffersNumber: "8"
  defaultConnString: "Host=eh-st-postgresql;Port=5435;Database=EventHub;Username=root;Password=root"
  redisConfiguration: "eh-st-redis"
  internalAuthServerAuthority: "http://eh-st-account"
  internalAuthServerRequireHttpsMetadata: "false"
  stringEncryptionDefaultPassPhrase: "TxVIZFPxK33czbbv"
account:
  containerImage: "eventhub.account"
api:
  containerImage: "eventhub.api"
www:
  containerImage: "eventhub.www"
dbmigrator:
  containerImage: "eventhub.dbmigrator"