apiVersion: v1
kind: Service
metadata:
  name: volosoft-eventhub-identityserver-service
spec:
  selector:
    app: volosoft-eventhub-identityserver-pod
  ports:
  - name: http
    port: 5001
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP 
  type: LoadBalancer