apiVersion: v1
kind: Service
metadata:
  name: volosoft-eventhub-httpapi-host-service
spec:
  selector:
    app: volosoft-eventhub-httpapi-host-pod
  ports:
  - port: 5002
    targetPort: 5002
  type: LoadBalancer
