apiVersion: v1
kind: Service
metadata:
  labels:
    name: postgresql
  name: postgresql
spec:
  type: LoadBalancer
  ports:
    - name: postgresql
      port: 5435
      targetPort: 5432
  selector:
    app: postgresql

