apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: eventhub.api
        imagePullPolicy: Never
        name: api
        ports:
        - name: apihttp
          containerPort: 80
        - name: apihttps
          containerPort: 443